Feat/hotkey
smartmind-team/thanosql-editor pull request #4
Opened 2023-04-27 07:36 UTC by nokchalatte

- Add (non-default) hotkeys to editor

Supported commands:
- `Cmd` + `A` select all -> default, no need to add
- `Cmd` + `/` toggle line comment -> default, no hotkeys added, only comment rule in `setup.ts`
- `Cmd` + `-` font zoom out
- `Cmd` + `=` font zoom in
- `Cmd` + `0` font zoom reset
- `Cmd` + `Enter` run selected (highlighted/dragged/blocked) code

2023-04-27 10:44 UTC, lazyduo commented on src/components/Editor/Editor.tsx
> +          var val = model.getValueInRange(editor.getSelection());
getSelection 결과가 없으면 전체 실행하게 해주세요~

2023-05-02 10:12 UTC, ss-won requested changes
고생하셨습니다 ~ 🙂 몇가지 코멘트 반영 부탁해요

2023-05-02 10:12 UTC, ss-won commented on src/components/Editor/Editor.tsx
Do not use `var` keyword please! replace it let or const
[why don't we use var anymore](https://medium.com/@codingsam/awesome-javascript-no-more-var-working-title-999428999994)

2023-05-02 10:12 UTC, ss-won commented on src/components/Editor/Editor.tsx
> +      var editor = monaco.editor.create(divNode, {
```suggestion
      const editor = monaco.editor.create(divNode, {
```

2023-05-02 10:12 UTC, ss-won commented on src/components/Editor/Editor.tsx
> +      var model = editor.getModel();
```suggestion
      const model = editor.getModel();
```

2023-05-02 10:12 UTC, ss-won commented on src/components/Editor/Editor.tsx
> +      editor.addAction(executeAction)
```suggestion
      const executeAction: monaco.editor.IActionDescriptor = {
        id: "executeSelectedCode",
        label: "Execute selected code",
        contextMenuOrder: 2,
        contextMenuGroupId: "1_modification",
        keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter],
        run: (editor) => {
          // by default, only run selected value
          let selectedValue = model.getValueInRange(editor.getSelection());
          // however, if nothing is selected, we run all editor value
          if (val === "") {
            selectedValue = model.getValue();
          }
          onStartQuery && onStartQuery(editor, targetValue);
        },
      }
    
      editor.addAction(executeAction)
```

2023-05-02 10:12 UTC, ss-won commented on src/components/EditorLauncher/EditorLauncher.tsx
>    method(editor?: monaco.editor.IStandaloneCodeEditor): void;
```suggestion
  method(editor?: monaco.editor.IStandaloneCodeEditor, targetValue?: string): void;
```

2023-05-03 08:16 UTC, nokchalatte commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
블록 실행 is not working if I don't use this code.. any suggestions?

2023-05-03 09:04 UTC, ss-won commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
```suggestion
          let selectedElem = document.createElement("div");
          let selectedEditor = monaco.editor.create(selectedElem, {value: selectedValue});
          onStartQuery && onStartQuery(selectedEditor);
```

umm..I think then make code that get selection value to module.
```ts
//Editor.tsx
...
const startQuery:typeof onStartQuery = (editor, selectedValue) => { 
// by default, only run selected value
let selectedValue = model.getValueInRange(editor.getSelection());
// however, if nothing is selected, we run all editor value
if (selectedValue === "") {
  selectedValue = model.getValue();
}
return onStartQuery(editor, selectedValue);
}

const executeAction: monaco.editor.IActionDescriptor = {
  id: "executeSelectedCode",
  label: "Execute selected code",
  contextMenuOrder: 2,
  contextMenuGroupId: "1_modification",
  keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter],
  run: startQuery
}

editor.addAction(executeAction)

...
 return (
    <div
      className="editor-wrapper"
      style={{ display: "flex", flexFlow: "column nowrap", height: "100%" }}
    >
      <EditorLauncher onStartQuery={startQuery} onStopQuery={onStopQuery} />
...
```

``Àpp.tsx
import Editor from "@smartmind-team/thanosql-editor";
import { useEditorContext } from "@smartmind-team/thanosql-editor";

function App() {
  const { isQueryStarting, editor, setQueryStarting } = useEditorContext();

  return (
    <div
      className="App"
      style={{
        width: "100vw",
        height: "100vh",
        display: "flex",
        flexFlow: "column nowrap",
      }}
    >
      <div style={{ fontSize: "1rem", fontWeight: 900 }}>Editor Example</div>
      <div style={{ flex: 2 }}>
        <Editor
          language="thanosql"
          workerPaths={{
            default: {
              url: "../node_modules/monaco-editor-core/esm/vs/editor/editor.worker.js",
              base: window.location.href,
              isModule: true,
            },
            thanosql: {
              url: "../node_modules/@smartmind-team/thanosql-editor/lib/esm/thanosql/thanos.worker.js",
              base: window.location.href,
              isModule: true,
            },
          }}
          onStartQuery={(editor, targetValue) => {
            setQueryStarting(true);
            console.log(targetValue);
            setTimeout(() => setQueryStarting(false), 2000);
          }}
        />
      </div>
    </div>
  );
}

export default App;
```

I think this code is solve it..

2023-05-03 09:20 UTC, ss-won commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
Editor needs entire refactoring, so if this code is not working, just merge code below. 🙂
```ts
let selectedElem = document.createElement("div");
let selectedEditor = monaco.editor.create(selectedElem, {value: selectedValue});
onStartQuery && onStartQuery(selectedEditor);
```

2023-05-03 09:20 UTC, ss-won approved these changes

2023-05-03 11:03 UTC, nokchalatte commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
I see.. what does @lazyduo think?

2023-05-03 11:12 UTC, lazyduo commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
나 왜 소환된거지..ㅋㅋ @ss-won 내일 설명 좀 부탁해요..

2023-05-03 12:14 UTC, ss-won commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
아 이거 제 생각에는..ctrl+enter=그냥 일반 실행(start 버튼 누르기)이랑 같은 동작을해야한다고 생각해서 targetValue만 넘기고 실제 동작 제어는 에디터를 실제 사용하는 부분에서 하려고했는데

Chrysan 설계대로 selection 부분 실행(버튼 누르는 동작은 전체 코드 실행)이라고 한다면 해당 내용 그대로 적용하는게 맞는 것 같아요 :) 내일 다시 이야기 하는걸로…

2023-05-03 12:20 UTC, lazyduo commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
음 selection 있는 경우 버튼을 클릭하든 cmd + enter를 하든 둘다 selection 부분을 돌려야해요. 저도 확실하게는 기억이 잘 안나서 내일 빅쿼리랑 pgadmin 돌려보고 알려드릴게요ㅋㅋ

2023-05-03 23:51 UTC, lazyduo commented on src/components/Editor/Editor.tsx
> +          onStartQuery && onStartQuery(selectedEditor);
pgAdmin, 빅쿼리 모두 기본적으로 '실행' 버튼과 단축키는 동일하게 동작합니다. 블록(selection)이 있을 경우 버튼이든 단축키든 '실행'의 경우 블록만 실행됩니다. 마찬가지로 버튼이든 단축키든 블록이 없을 경우는 전체 실행이구요

2023-05-04 05:26 UTC, ss-won approved these changes
good 👍🏻 LGTM

2023-05-10 00:06 UTC, lazyduo approved these changes

2023-05-16 10:01 UTC, merged